apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: node-frontend
    spec:
      containers:
        - name: node-container-frontend
          image: sa-saopaulo-1.ocir.io/grkxqqgi0ewn/csp-registry/my-aplication:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: node-frontend
